CATEGORIES = {
  'Name'                 => 'string',
  'Artist'               => 'string',
  'Album Artist'         => 'string',
  'Album'                => 'string',
  'Grouping'             => 'string',
  'Genre'                => 'string',
  'Kind'                 => 'string',
  'Equalizer'            => 'string',
  'Sort Name'            => 'string',
  'Persistent ID'        => 'string',
  'Track Type'           => 'string',
  'Location'             => 'string',
  'Track ID'             => 'integer',
  'Size'                 => 'integer',
  'Total Time'           => 'integer',
  'Disc Number'          => 'integer',
  'Disc Count'           => 'integer',
  'Track Number'         => 'integer',
  'Track Count'          => 'integer',
  'Year'                 => 'integer',
  'BPM'                  => 'integer',
  'Bit Rate'             => 'integer',
  'Sample Rate'          => 'integer',
  'Play Count'           => 'integer',
  'Play Date'            => 'integer',
  'Skip Count'           => 'integer',
  'Rating'               => 'integer',
  'Artwork Count'        => 'integer',
  'File Type'            => 'integer',
  'File Folder Count'    => 'integer',
  'Library Folder Count' => 'integer',
  'Date Modified'        => 'date',
  'Date Added'           => 'date',
  'Play Date UTC'        => 'date',
  'Skip Date'            => 'date'
}

DISPLAY = [
  'Name',
  'Artist',
  'Album Artist',
  'Album',
#  'Grouping',
#  'Genre',
#  'Kind',
#  'Equalizer',
#  'Sort Name',
#  'Persistent ID',
#  'Track Type',
#  'Location',
#  'Track ID',
#  'Size',
#  'Total Time',
#  'Disc Number',
#  'Disc Count',
#  'Track Number',
#  'Track Count',
  'Year',
#  'BPM',
#  'Bit Rate',
#  'Sample Rate',
  'Play Count',
  'Play Date', # seconds since 1/1/1904
#  'Skip Count',
#  'Rating',
#  'Artwork Count',
#  'File Type',
#  'File Folder Count',
#  'Library Folder Count',
 'Date Modified',
 'Date Added',
 'Play Date UTC',
#  'Skip Date'
]
